/* AUTO-GENERATED from audit JSON: route-audit-20260301-142122.json
 * Generated: 20260301-144151
 * Do not edit by hand; re-run Link Visibility Pack.
 */

export type RouteIndexItem = {
  path: string;
  normalized?: string;
  component?: string;
  file?: string;
  lastGit?: string;
};

export const ROUTE_INDEX: RouteIndexItem[] = [
  { path: "*", normalized: "*", component: "", file: "", lastGit: "" },
  { path: "/", normalized: "", component: "AuthLandingPage", file: ".\\src\\pages\\AuthLandingPage.tsx", lastGit: "" },
  { path: "/alliances", normalized: "/alliances", component: "AllianceDirectoryPage", file: ".\\src\\pages\\alliance\\AllianceDirectoryPage.tsx", lastGit: "" },
  { path: "/alliances-v2", normalized: "/alliances", component: "AllianceDirectoryDbPage", file: ".\\src\\pages\\alliance\\AllianceDirectoryDbPage.tsx", lastGit: "" },
  { path: "/dashboard", normalized: "/dashboard", component: "DashboardEntry", file: "", lastGit: "" },
  { path: "/dashboard/:alliance_id", normalized: "/dashboard/:alliance_id", component: "DashboardLayout", file: ".\\src\\layouts\\DashboardLayout.tsx", lastGit: "" },
  { path: "/dashboard/ME", normalized: "/dashboard/ME", component: "", file: "", lastGit: "" },
  { path: "/debug", normalized: "/debug", component: "DebugPage", file: ".\\src\\pages\\DebugPage.tsx", lastGit: "" },
  { path: "/mail", normalized: "/mail", component: "MyMailPage", file: ".\\src\\pages\\mail\\MyMailPage.tsx", lastGit: "" },
  { path: "/mail-threads", normalized: "/mail-threads", component: "MyMailThreadsPage", file: ".\\src\\pages\\mail\\MyMailThreadsPage.tsx", lastGit: "" },
  { path: "/mail-v2", normalized: "/mail", component: "MyMailInboxPage", file: ".\\src\\pages\\mail\\MyMailInboxPage.tsx", lastGit: "" },
  { path: "/me", normalized: "/me", component: "PlayerDashboardSafePage", file: ".\\src\\pages\\PlayerDashboardSafePage.tsx", lastGit: "" },
  { path: "/me/hq-manager", normalized: "/me/hq-manager", component: "MyHqManagerPage", file: ".\\src\\pages\\me\\MyHqManagerPage.tsx", lastGit: "" },
  { path: "/onboarding", normalized: "/onboarding", component: "RequestAccessPage", file: ".\\src\\pages\\onboarding\\RequestAccessPage.tsx", lastGit: "" },
  { path: "/owner", normalized: "/owner", component: "OwnerDashboardPage", file: ".\\src\\pages\\owner\\OwnerDashboardPage.tsx", lastGit: "" },
  { path: "/owner/access-control", normalized: "/owner/access-control", component: "OwnerAccessControlPage", file: ".\\src\\pages\\owner\\OwnerAccessControlPage.tsx", lastGit: "" },
  { path: "/owner/achievements/access", normalized: "/owner/achievements/access", component: "OwnerAchievementAccessPage", file: ".\\src\\pages\\owner\\OwnerAchievementAccessPage.tsx", lastGit: "" },
  { path: "/owner/achievements/config", normalized: "/owner/achievements/config", component: "OwnerAchievementConfigPage", file: ".\\src\\pages\\owner\\OwnerAchievementConfigPage.tsx", lastGit: "" },
  { path: "/owner/achievements/requests", normalized: "/owner/achievements/requests", component: "OwnerAchievementRequestsPage", file: ".\\src\\pages\\owner\\OwnerAchievementRequestsPage.tsx", lastGit: "" },
  { path: "/owner/activity-feed", normalized: "/owner/activity-feed", component: "OwnerActivityFeedPage", file: ".\\src\\pages\\owner\\OwnerActivityFeedPage.tsx", lastGit: "" },
  { path: "/owner/alliance-directory", normalized: "/owner/alliance-directory", component: "OwnerAllianceDirectoryEditorPage", file: ".\\src\\pages\\owner\\OwnerAllianceDirectoryEditorPage.tsx", lastGit: "" },
  { path: "/owner/alliances", normalized: "/owner/alliances", component: "OwnerAlliancesPage", file: ".\\src\\pages\\owner\\OwnerAlliancesPage.tsx", lastGit: "" },
  { path: "/owner/broadcast", normalized: "/owner/broadcast", component: "OwnerBroadcastComposerPage", file: ".\\src\\pages\\owner\\OwnerBroadcastComposerPage.tsx", lastGit: "" },
  { path: "/owner/command-center", normalized: "/owner/command-center", component: "OwnerCommandCenterV2Page", file: ".\\src\\pages\\owner\\OwnerCommandCenterV2Page.tsx", lastGit: "" },
  { path: "/owner/data-vault", normalized: "/owner/data-vault", component: "OwnerDataVaultPage", file: ".\\src\\pages\\owner\\OwnerDataVaultPage.tsx", lastGit: "" },
  { path: "/owner/directory-db", normalized: "/owner/directory", component: "OwnerDirectoryDbPage", file: ".\\src\\pages\\owner\\OwnerDirectoryDbPage.tsx", lastGit: "" },
  { path: "/owner/directory-editor", normalized: "/owner/directory-editor", component: "OwnerAllianceDirectoryEditorPage", file: ".\\src\\pages\\owner\\OwnerAllianceDirectoryEditorPage.tsx", lastGit: "" },
  { path: "/owner/directory-sync", normalized: "/owner/directory-sync", component: "OwnerAllianceDirectorySyncPage", file: ".\\src\\pages\\owner\\OwnerAllianceDirectorySyncPage.tsx", lastGit: "" },
  { path: "/owner/discord", normalized: "/owner/discord", component: "OwnerDiscordSettingsPage", file: ".\\src\\pages\\owner\\OwnerDiscordSettingsPage.tsx", lastGit: "" },
  { path: "/owner/discord-defaults", normalized: "/owner/discord-defaults", component: "OwnerDiscordDefaultsPage", file: ".\\src\\pages\\owner\\OwnerDiscordDefaultsPage.tsx", lastGit: "" },
  { path: "/owner/discord-edge-test", normalized: "/owner/discord-edge-test", component: "OwnerDiscordEdgeSendTestPage", file: ".\\src\\pages\\owner\\OwnerDiscordEdgeSendTestPage.tsx", lastGit: "" },
  { path: "/owner/discord-mentions", normalized: "/owner/discord-mentions", component: "OwnerDiscordMentionsPage", file: ".\\src\\pages\\owner\\OwnerDiscordMentionsPage.tsx", lastGit: "" },
  { path: "/owner/discord-mentions-tools", normalized: "/owner/discord-mentions-tools", component: "OwnerDiscordMentionsToolsPage", file: ".\\src\\pages\\owner\\OwnerDiscordMentionsToolsPage.tsx", lastGit: "" },
  { path: "/owner/discord-queue", normalized: "/owner/discord-queue", component: "OwnerDiscordQueuePage", file: ".\\src\\pages\\owner\\OwnerDiscordQueuePage.tsx", lastGit: "" },
  { path: "/owner/discord-send-log", normalized: "/owner/discord-send-log", component: "OwnerDiscordSendLogPage", file: ".\\src\\pages\\owner\\OwnerDiscordSendLogPage.tsx", lastGit: "" },
  { path: "/owner/discord-templates", normalized: "/owner/discord-templates", component: "OwnerDiscordTemplatesPage", file: ".\\src\\pages\\owner\\OwnerDiscordTemplatesPage.tsx", lastGit: "" },
  { path: "/owner/discord-test-send", normalized: "/owner/discord-test-send", component: "OwnerDiscordTestSendPage", file: ".\\src\\pages\\owner\\OwnerDiscordTestSendPage.tsx", lastGit: "" },
  { path: "/owner/event-reminders", normalized: "/owner/event-reminders", component: "OwnerEventRemindersPage", file: ".\\src\\pages\\owner\\OwnerEventRemindersPage.tsx", lastGit: "" },
  { path: "/owner/event-types", normalized: "/owner/event-types", component: "OwnerEventTypesPage", file: ".\\src\\pages\\owner\\OwnerEventTypesPage.tsx", lastGit: "" },
  { path: "/owner/event-types-library", normalized: "/owner/event-types-library", component: "OwnerEventTypesLibraryPage", file: ".\\src\\pages\\owner\\OwnerEventTypesLibraryPage.tsx", lastGit: "" },
  { path: "/owner/jump", normalized: "/owner/jump", component: "OwnerAllianceJumpPage", file: ".\\src\\pages\\owner\\OwnerAllianceJumpPage.tsx", lastGit: "" },
  { path: "/owner/live-ops", normalized: "/owner/live-ops", component: "OwnerLiveOpsPage", file: ".\\src\\pages\\owner\\OwnerLiveOpsPage.tsx", lastGit: "" },
  { path: "/owner/live-ops-db", normalized: "/owner/live-ops", component: "OwnerLiveOpsDbPage", file: ".\\src\\pages\\owner\\OwnerLiveOpsDbPage.tsx", lastGit: "" },
  { path: "/owner/mail-broadcast", normalized: "/owner/mail-broadcast", component: "OwnerMailBroadcastPage", file: ".\\src\\pages\\owner\\OwnerMailBroadcastPage.tsx", lastGit: "" },
  { path: "/owner/membership", normalized: "/owner/membership", component: "OwnerMembershipManagerPage", file: ".\\src\\pages\\owner\\OwnerMembershipManagerPage.tsx", lastGit: "" },
  { path: "/owner/memberships", normalized: "/owner/memberships", component: "OwnerMembershipsPage", file: ".\\src\\pages\\owner\\OwnerMembershipsPage.tsx", lastGit: "" },
  { path: "/owner/onboarding-queue", normalized: "/owner/onboarding-queue", component: "OwnerOnboardingQueuePage", file: ".\\src\\pages\\owner\\OwnerOnboardingQueuePage.tsx", lastGit: "" },
  { path: "/owner/oneclick-provision", normalized: "/owner/oneclick-provision", component: "OwnerOneClickProvisionPage", file: ".\\src\\pages\\owner\\OwnerOneClickProvisionPage.tsx", lastGit: "" },
  { path: "/owner/oneclick-provision-plus", normalized: "/owner/oneclick-provision-plus", component: "OwnerOneClickProvisionPlusPage", file: ".\\src\\pages\\owner\\OwnerOneClickProvisionPlusPage.tsx", lastGit: "" },
  { path: "/owner/permissions?section=permissions", normalized: "/owner/permissions", component: "", file: "", lastGit: "" },
  { path: "/owner/permissions?section=permissions", normalized: "/owner/permissions-matrix", component: "", file: "", lastGit: "" },
  { path: "/owner/permissions", normalized: "/owner/permissions?section=permissions", component: "", file: "", lastGit: "" },
  { path: "/owner/permissions?section=permissions-v3", normalized: "/owner/permissions?section=permissions", component: "OwnerPermissionsMatrixV3Page", file: ".\\src\\pages\\owner\\OwnerPermissionsMatrixV3Page.tsx", lastGit: "" },
  { path: "/owner/player-intake", normalized: "/owner/player-intake", component: "OwnerPlayerIntakePage", file: ".\\src\\pages\\owner\\OwnerPlayerIntakePage.tsx", lastGit: "" },
  { path: "/owner/players", normalized: "/owner/players", component: "OwnerPlayersPage", file: ".\\src\\pages\\owner\\OwnerPlayersPage.tsx", lastGit: "" },
  { path: "/owner/players-link", normalized: "/owner/players-link", component: "OwnerPlayersLinkPage", file: ".\\src\\pages\\owner\\OwnerPlayersLinkPage.tsx", lastGit: "" },
  { path: "/owner/realtime-history", normalized: "/owner/realtime-history", component: "OwnerRealtimeHistoryPage", file: ".\\src\\pages\\owner\\OwnerRealtimeHistoryPage.tsx", lastGit: "" },
  { path: "/owner/requests", normalized: "/owner/requests", component: "OwnerAccessRequestsPage", file: ".\\src\\pages\\owner\\OwnerAccessRequestsPage.tsx", lastGit: "" },
  { path: "/owner/requests-provision", normalized: "/owner/requests-provision", component: "OwnerRequestsProvisionPage", file: ".\\src\\pages\\owner\\OwnerRequestsProvisionPage.tsx", lastGit: "" },
  { path: "/owner/roles", normalized: "/owner/roles", component: "OwnerRolesPermissionsV2Page", file: ".\\src\\pages\\owner\\OwnerRolesPermissionsV2Page.tsx", lastGit: "" },
  { path: "/owner/scheduled-sends", normalized: "/owner/scheduled-sends", component: "OwnerScheduledDiscordSendsPage", file: ".\\src\\pages\\owner\\OwnerScheduledDiscordSendsPage.tsx", lastGit: "" },
  { path: "/owner/select", normalized: "/owner/select", component: "OwnerDashboardSelect", file: ".\\src\\pages\\OwnerDashboardSelect.tsx", lastGit: "" },
  { path: "/owner/state", normalized: "/owner/state", component: "OwnerStateManagerPage", file: ".\\src\\pages\\owner\\OwnerStateManagerPage.tsx", lastGit: "" },
  { path: "/owner/state-achievement-catalog", normalized: "/owner/state-achievement-catalog", component: "OwnerStateAchievementCatalogPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementCatalogPage.tsx", lastGit: "" },
  { path: "/owner/state-achievement-inbox", normalized: "/owner/state-achievement-inbox", component: "OwnerStateAchievementInboxPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementInboxPage.tsx", lastGit: "" },
  { path: "/owner/state-achievement-requests", normalized: "/owner/state-achievement-requests", component: "OwnerStateAchievementRequestsPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementRequestsPage.tsx", lastGit: "" },
  { path: "/owner/state-achievements", normalized: "/owner/state-achievements", component: "OwnerStateAchievementsPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementsPage.tsx", lastGit: "" },
  { path: "/owner/state-achievements-roster", normalized: "/owner/state-achievements-roster", component: "OwnerStateAchievementsRosterPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementsRosterPage.tsx", lastGit: "" },
  { path: "/owner/state-achievements/access", normalized: "/owner/state-achievements/access", component: "OwnerStateAchievementsAccessPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementsAccessPage.tsx", lastGit: "" },
  { path: "/owner/state-achievements/admin", normalized: "/owner/state-achievements/admin", component: "OwnerStateAchievementsAdminPage", file: ".\\src\\pages\\owner\\OwnerStateAchievementsAdminPage.tsx", lastGit: "" },
  { path: "/owner/state-achievements/queue", normalized: "/owner/state-achievements/queue", component: "OwnerStateAchievementsQueuePage", file: ".\\src\\pages\\owner\\OwnerStateAchievementsQueuePage.tsx", lastGit: "" },
  { path: "/owner/state-leaders", normalized: "/owner/state-leaders", component: "OwnerStateLeadersAdminPage", file: ".\\src\\pages\\owner\\OwnerStateLeadersAdminPage.tsx", lastGit: "" },
  { path: "/state", normalized: "/state", component: "", file: "", lastGit: "" },
  { path: "/state/:state_code/alerts-db", normalized: "/state/:state_code/alerts", component: "StateAlertsDbPage", file: ".\\src\\pages\\state\\StateAlertsDbPage.tsx", lastGit: "" },
  { path: "/state/:state_code/discussion-db", normalized: "/state/:state_code/discussion", component: "StateDiscussionDbPage", file: ".\\src\\pages\\state\\StateDiscussionDbPage.tsx", lastGit: "" },
  { path: "/state/:state_code/ops-db", normalized: "/state/:state_code/ops", component: "StateOpsBoardDbPage", file: ".\\src\\pages\\state\\StateOpsBoardDbPage.tsx", lastGit: "" },
  { path: "/state/789", normalized: "/state/789", component: "State789DashboardPage", file: ".\\src\\pages\\state\\State789DashboardPage.tsx", lastGit: "" },
  { path: "/state/789/achievement-request", normalized: "/state/789/achievement-request", component: "State789AchievementRequestPage", file: ".\\src\\pages\\state\\State789AchievementRequestPage.tsx", lastGit: "" },
  { path: "/state/789/achievements", normalized: "/state/789/achievements", component: "State789AchievementsPage", file: ".\\src\\pages\\state\\State789AchievementsPage.tsx", lastGit: "" },
  { path: "/state/789/achievements-form", normalized: "/state/789/achievements-form", component: "State789AchievementsFormPage", file: ".\\src\\pages\\state\\State789AchievementsFormPage.tsx", lastGit: "" },
  { path: "/state/789/achievements-progress", normalized: "/state/789/achievements-progress", component: "State789AchievementsProgressPage", file: ".\\src\\pages\\state\\State789AchievementsProgressPage.tsx", lastGit: "" },
  { path: "/state/789/achievements-tracker", normalized: "/state/789/achievements-tracker", component: "State789AchievementsTrackerPage", file: ".\\src\\pages\\state\\State789AchievementsTrackerPage.tsx", lastGit: "" },
  { path: "/state/789/achievements/admin-v2", normalized: "/state/789/achievements/admin", component: "State789AchievementsAdminV2Page", file: ".\\src\\pages\\state\\State789AchievementsAdminV2Page.tsx", lastGit: "" },
  { path: "/state/789/achievements/request", normalized: "/state/789/achievements/request", component: "State789AchievementRequestPage", file: ".\\src\\pages\\state\\State789AchievementRequestPage.tsx", lastGit: "" },
  { path: "/state/789/achievements/request-v2", normalized: "/state/789/achievements/request", component: "State789AchievementRequestV2Page", file: ".\\src\\pages\\state\\State789AchievementRequestV2Page.tsx", lastGit: "" },
  { path: "/state/789/alerts", normalized: "/state/789/alerts", component: "State789AlertsPage", file: ".\\src\\pages\\state\\State789AlertsPage.tsx", lastGit: "" },
  { path: "/state/789/alerts-db", normalized: "/state/789/alerts", component: "State789AlertsDbPage", file: ".\\src\\pages\\state\\State789AlertsDbPage.tsx", lastGit: "" },
  { path: "/state/789/alerts-v2", normalized: "/state/789/alerts", component: "State789AlertsCenterPage", file: ".\\src\\pages\\state\\State789AlertsCenterPage.tsx", lastGit: "" },
  { path: "/state/789/discussion", normalized: "/state/789/discussion", component: "State789DiscussionBoardPage", file: ".\\src\\pages\\state\\State789DiscussionBoardPage.tsx", lastGit: "" },
  { path: "/state/789/discussion-db", normalized: "/state/789/discussion", component: "State789DiscussionDbPage", file: ".\\src\\pages\\state\\State789DiscussionDbPage.tsx", lastGit: "" },
  { path: "/state/789/discussion-v2", normalized: "/state/789/discussion", component: "State789DiscussionBoardV2Page", file: ".\\src\\pages\\state\\State789DiscussionBoardV2Page.tsx", lastGit: "" },
  { path: "/state/789/ops", normalized: "/state/789/ops", component: "State789OpsConsolePage", file: ".\\src\\pages\\state\\State789OpsConsolePage.tsx", lastGit: "" },
  { path: "/state/789/ops-db", normalized: "/state/789/ops", component: "StateOpsBoardDbPage", file: ".\\src\\pages\\state\\StateOpsBoardDbPage.tsx", lastGit: "" },
  { path: "/state/789/progress", normalized: "/state/789/progress", component: "State789AchievementProgressPage", file: ".\\src\\pages\\state\\State789AchievementProgressPage.tsx", lastGit: "" },
  { path: "/status", normalized: "/status", component: "SystemStatusPage", file: ".\\src\\pages\\SystemStatusPage.tsx", lastGit: "" },
  { path: "alerts", normalized: "alerts", component: "AllianceAlertsPage", file: ".\\src\\pages\\alliance\\AllianceAlertsPage.tsx", lastGit: "" },
  { path: "announcements", normalized: "announcements", component: "AllianceAnnouncementsPage", file: ".\\src\\pages\\alliance\\AllianceAnnouncementsPage.tsx", lastGit: "" },
  { path: "calendar", normalized: "calendar", component: "AllianceCalendarPage", file: ".\\src\\pages\\calendar\\AllianceCalendarPage.tsx", lastGit: "" },
  { path: "events", normalized: "events", component: "EventsPage", file: ".\\src\\pages\\EventsPage.tsx", lastGit: "" },
  { path: "guides", normalized: "guides", component: "AllianceGuidesPage", file: ".\\src\\pages\\alliance\\AllianceGuidesPage.tsx", lastGit: "" },
  { path: "hq-map", normalized: "hq-map", component: "AllianceHQMap", file: ".\\src\\pages\\dashboard\\AllianceHQMap.tsx", lastGit: "" },
  { path: "permissions", normalized: "permissions", component: "PermissionsPage", file: ".\\src\\pages\\dashboard\\Permissions.tsx", lastGit: "" },
  { path: "roster", normalized: "roster", component: "AllianceRosterPage", file: ".\\src\\pages\\alliance\\AllianceRosterPage.tsx", lastGit: "" },
];

export const OWNER_ROUTE_INDEX = ROUTE_INDEX.filter(r => r.path === "/owner" || r.path.startsWith("/owner/"));
export const STATE_ROUTE_INDEX = ROUTE_INDEX.filter(r => r.path.startsWith("/state/") || r.path === "/state");
export const PLAYER_ROUTE_INDEX = ROUTE_INDEX.filter(r => r.path === "/me" || r.path.startsWith("/me/") || r.path.StartsWith("/mail") || r.path.StartsWith("/dashboard"));



